[build]
command = "npm run build"
functions = "functions"
publish = "dist"

[dev]
    port = 3002
    targetPort = 3000

[functions]
    node_bundler = "esbuild"

[[headers]]
for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Referrer-Policy = "same-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
for = "/assets/*"
    [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''

[[headers]]
for = "/manifest.webmanifest"
    [headers.values]
    Content-Type = "application/manifest+json"
