[build]
command = 'npm run build'
publish = 'dist'

[dev]
port = 4000
targetPort = 3000

[[headers]]
for = '/*'
[headers.values]
Access-Control-Allow-Origin = '*'
Referrer-Policy = 'same-origin'
X-Content-Type-Options = 'nosniff'
X-Frame-Options = 'SAMEORIGIN'

[[headers]]
for = '/public/*'
[headers.values]
cache-control = '''
    max-age=31536000
    immutable
    '''

[[headers]]
for = '/manifest.webmanifest'
[headers.values]
Content-Type = 'application/manifest+json'
